### ISSUE TITLE
Multiple LUKS Containers

### ISSUE THREAD

**Issue by fringerdarlinger** [tokiclover/mkinitramfs-ll#38]
Considering switching using your project for my setup. Does mkinitramfs-ll support multiple luks containers? I have two hard drives in my laptop. Also, does it support detached headers for both of them?

**Comment by tokiclover** [comment]
Yes for both questions and it does support multiple key(-file)s in
multiple mode. See mkinitramfs-ll(1) manual page for more info.

Note that, to support multiple containers,--up to three groups,--using
`swap` or `resume` group may be necessary which does not mean or equal
to using a swap or a resume container or partition at all. If you need
those containers to be mounted, you would have to use `fsmount` kernel
command line wich is not realy necessary because once the root
filesystem is mounted, the init system would take care of it without any
hassle.

So, usually, the initramfs would take care of mounting the rootfs and
unlock swap and resume containers beforehand to be ready for complicated
setups.
